project:
  type: website
  output-dir: docs

website:
  title: "Haini Wen"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV
  page-footer:
    center: "© Haini Wen · Uppsala University"

format:
  html:
    theme: cosmo
    toc: false